#config_version=5

shot_profiles:
  skill_shot_profile:
    advance_on_hit: false
    states:
      - name: off
        show:
      - name: lit
        show: flash_colors
        speed: 3
        show_tokens:
          color1: red
          color2: stop
