#config_version=5

achievements:
  attack_left:
    show_tokens:
      led: l_attack_left_achievement
    show_when_started: flash
    show_when_completed: on
    complete_events: quest_attack_left_complete
    start_events: mode_quest_attack_left_started
  attack_right:
    show_tokens:
      led: l_attack_right_achievement
    show_when_started: flash
    show_when_completed: on
    complete_events: quest_attack_right_complete
    start_events: mode_quest_attack_right_started
  scale_walls:
    show_tokens:
      led: l_scale_walls_achievement
    show_when_started: flash
    show_when_completed: on
    complete_events: quest_scale_walls_complete
    start_events: mode_quest_scale_walls_started
  mass_attack:
    show_tokens:
      led: l_mass_attack_achievement
    show_when_started: flash
    show_when_completed: on
    complete_events: quest_mass_attack_complete
    start_events: mode_quest_mass_attack_started
  drain_moat:
    show_tokens:
      led: l_drain_moat_achievement
    show_when_started: flash
    show_when_completed: on
    complete_events: quest_drain_moat_complete
    start_events: mode_quest_drain_moat_started
  quench_fire:
    show_tokens:
      led: l_quench_fire_achievement
    show_when_started: flash
    show_when_completed: on
    complete_events: quest_quench_fire_complete
    start_events: mode_quest_quench_fire_started
  archer_attack:
    show_tokens:
      led: l_archer_attack_achievement
    show_when_started: flash
    show_when_completed: on
    complete_events: archer_attack_complete
    start_events: mode_archer_attack_started