#config_version=5

config:
  - mode.yaml
  - slide_player.yaml
  - variable_player.yaml
  - widgets.yaml
  - widget_player.yaml
  - achievements.yaml
  - multiball_locks.yaml
  - ball_saves.yaml
  - multiballs.yaml