#config_version=5

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: TEST
      # - type: text
      #   text: PLAYER 1
      #   font_size: 15
      #   y: top-2
      #   x: 5
      #   anchor_x: left
      #   anchor_y: top
      # - type: text
      #   text: (player1|score)
      #   number_grouping: true
      #   min_digits: 4
      #   font_size: 15
      #   y: top-2
      #   x: right-5
      #   anchor_x: right
      #   anchor_y: top
      # - type: text
      #   text: PLAYER 2
      #   font_size: 15
      #   y: top-17
      #   x: 5
      #   anchor_x: left
      #   anchor_y: top
      # - type: text
      #   text: (player2|score)
      #   number_grouping: true
      #   min_digits: 4
      #   font_size: 15
      #   y: top-17
      #   x: right-5
      #   anchor_x: right
      #   anchor_y: top
      # - type: text
      #   text: BALL (ball)
      #   y: 2
      #   anchor_y: bottom
      #   font_size: 15
