#config_version=5

widgets:
  player_1:
    - type: text
      text: Player 1
      x: 50
      y: top-20
      anchor_x: left
      anchor_y: top
      color: green
    - type: text
      text: (player1|score)
      number_grouping: true
      min_digits: 4
      x: right-50
      y: top-20
      anchor_x: right
      anchor_y: top
      color: green

widget_player:
  mode_base_started: 
    player_1:
      key: test
      widget_settings:
        color: 0000FF

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: Player 2
        x: 50
        y: top-220
        anchor_x: left
        anchor_y: top
      - type: text
        text: (player2|score)
        number_grouping: true
        min_digits: 4
        x: right-50
        y: top-220
        anchor_x: right
        anchor_y: top
      - type: text
        text: Ball (ball)
        y: 20
        anchor_y: bottom
