#config_version=5

shots:
  quest_attack_right:
    switch: s_right_shot_lane
    profile: flash_faster_each_hit_for_3_hits
    reset_events: quest_complete
    show_tokens:
      led: l_right_shot_lane
