#config_version=5

show_player:
  mode_qualify_for_select_quest_started: 
    flash:
      sync_ms: 1000
      speed: 3
      show_tokens:
        leds: l_front_gate_1, l_front_gate_2, l_front_gate_3
