#config_version=6

shots:
  heal_lane_1:
    switch: s_heal_lane_1
    profile: off_then_on_when_hit
    show_tokens:
      led: l_heal_lane_1
  heal_lane_2:
    switch: s_heal_lane_2
    profile: off_then_on_when_hit
    show_tokens:
      led: l_heal_lane_2
  heal_lane_3:
    switch: s_heal_lane_3
    profile: off_then_on_when_hit
    show_tokens:
      led: l_heal_lane_3
  heal_lane_4:
    switch: s_heal_lane_4
    profile: off_then_on_when_hit
    show_tokens:
      led: l_heal_lane_4
