#config_version=5

coils:
  c_flipper_left_main:
    number:
  c_flipper_left_hold:
    number:
    allow_enable: true
  c_flipper_right_main:
    number:
  c_flipper_right_hold:
    number:
    allow_enable: true
  c_trough_eject:
    number:
    default_pulse_ms: 20
  c_plunger:
    number:
    default_pulse_ms: 20
  c_heal_ball_save:
    number:
    default_pulse_ms: 20
