#config_version=5

mpf:
  report_crashes: never

config:
  - switches.yaml
  - coils.yaml
  - ball_devices.yaml
  - keyboard.yaml
  - sound_system.yaml
  - assets.yaml
  - sound_player.yaml
  - sounds.yaml
  - event_player.yaml
  - sound_pools.yaml
  - playfields.yaml
  - flippers.yaml
  - displays.yaml
  - slides.yaml
  - slide_player.yaml
  - modes.yaml
  - lights.yaml
  - shows.yaml
  - autofire_coils.yaml
  - window.yaml
  - widget_styles.yaml
  - shot_profiles.yaml
  - machine_vars.yaml
