#config_version=5

lights:
  l_top_lane_1:
    number:
  l_top_lane_2:
    number:
  l_top_lane_3:
    number:
  l_top_lane_4:
    number:
  l_heal_lane_1:
    number:
  l_heal_lane_2:
    number:
  l_heal_lane_3:
    number:
  l_heal_lane_4:
    number:
  l_heal_ball_save:
    number:
  l_start_button:
    number:
  l_front_gate:
    number:
  l_left_shot_lane:
    number:
  l_right_shot_lane:
    number:
  l_left_ramp:
    number:
  l_right_ramp:
    number:
  l_attack_left_achievement:
    number:
  l_attack_right_achievement:
    number:
  l_scale_walls_achievement:
    number: 
  l_mass_attack_achievement:
    number: 
  l_mob_1:
    number:
  l_mob_2:
    number:
  l_mob_3:
    number:
  l_side_gate:
    number:
  l_rear_gate:
    number:
  l_ore_1:
    number:
  l_ore_2:
    number:
  l_ore_3:
    number:
  l_catapult_lock:
    number: