#config_version=5

modes:
  - base
  - attract
  - skill_shot
  - top_lanes
  - heal_lanes
  - heal_ball_save
  - test
  - qualify_for_select_quest
  - select_quest
  - quest_attack_left
  - quest_attack_right
  - quest_scale_walls
  - skill_shot_hit
  - gather_mob
  - attack_side_gate
  - attack_rear_gate
  - quest_mass_attack
  - mine_ore
  - load_catapult
  - quest_drain_moat
  - quest_quench_fire
  - archer_attack
  - catapult_attack
  - quest_bonus
  - playfield_multiplier
  - ball_save
  - quest_attack_front_gate_1
  - quest_attack_front_gate_2
  - quest_attack_front_gate_3
  - final_battle
  - take_castle
  - tilt
  - bonus
  - bonus_multiplier