#config_version=5

shot_profiles:
  off_then_on_when_hit:
    advance_on_hit: true
    states:
      - name: off
        show: off
      - name: on
        show: on
  lit_flash:
    states:
      - name: lit
        show: flash
        sync_ms: 1000
        speed: 3
  flash_faster_each_hit_for_3_hits:
    advance_on_hit: true
    states:
      - name: one
        show: flash
        speed: 2
      - name: two
        show: flash
        speed: 3
      - name: last
        show: flash
        speed: 4
  off_then_lit_flash_keeping_current_color:
    advance_on_hit: false
    states:
      - name: off
        show:
      - name: lit
        show: flash_colors
        speed: 3
        sync_ms: 1000
        show_tokens:
          color1: red
          color2: stop
