#config_version=5

slides:
  welcome_slide:
    widgets:
      - type: text
        text: Castle Seige
        style: large
      - type: text
        text: by Eric Selk
        style: tiny
        y: 50
        anchor_y: bottom
