#config_version=6

sound_player:
  mode_attract_started:
    background_loop:
      action: play
      loops: -1
  mode_attract_stopped:
    background_loop:
      action: stop
  sw_start:
    arrow:
      action: play
