#config_version=6

sounds:
  # Music: 
  #  Lord of the Riffs 
  #  Ouroboros
  #  Tides of Iron
  #   by Alexander Nakarada (www.serpentsoundstudios.com)
  #   Licensed under Creative Commons BY Attribution 4.0 License
  #   https://creativecommons.org/licenses/by/4.0/
  #   $35 https://alexandernakarada.bandcamp.com/album/complete-discography-creative-commons-by-40
  background_loop:
    file: alexander-nakarada-lord-of-the-riffs.wav
  background_loop_2:
    file: alexander-nakarada-ouroboros.wav
  background_loop_3:
    file: alexander-nakarada-tides-of-iron.wav
  arrow1:
    file: arrow1.wav
  arrow2:
    file: arrow2.wav
  arrow3:
    file: arrow3.wav
  arrow4:
    file: arrow4.wav
  arrow5:
    file: arrow5.wav
  arrow6:
    file: arrow6.wav