#config_version=5

widget_styles:
  text_default:
    font_size: 10
    font_name: default
    line_height: 0.75
    adjust_top: 1
    adjust_bottom: 6
    z: 1
  tiny:
    font_size: 8
    font_name: small
    line_height: 0.9
    adjust_top: 0
    adjust_bottom: 2
    z: 1
