#config_version=6

shots:
  top_lane_1:
    switch: s_top_lane_1
    profile: off_then_on_when_hit
    show_tokens:
      led: l_top_lane_1
  top_lane_2:
    switch: s_top_lane_2
    profile: off_then_on_when_hit
    show_tokens:
      led: l_top_lane_2
  top_lane_3:
    switch: s_top_lane_3
    profile: off_then_on_when_hit
    show_tokens:
      led: l_top_lane_3
  top_lane_4:
    switch: s_top_lane_4
    profile: off_then_on_when_hit
    show_tokens:
      led: l_top_lane_4
