#config_version=5

shots:
  final_battle:
    switch: s_left_shot_lane
    profile: flash_faster_each_hit_for_3_hits
    reset_events: final_battle_complete
    show_tokens:
      led: l_left_shot_lane
