#config_version=5

mode:
  start_events:
    # final battle starts after all previous achievements are complete
    - qualified_for_select_quest{current_player.achievements_completed != 11}
  stop_events: select_quest_group_hit
  restart_on_next_ball: true
