#config_version=6

shot_groups:
  select_quest_group:
    shots: 
      - select_quest_attack_left
      - select_quest_attack_right
      - select_quest_scale_walls
      - select_quest_mass_attack
      - select_quest_drain_moat_left
      - select_quest_drain_moat_right
      - select_quest_quench_fire
