#config_version=6

shots:
  select_quest_attack_left:
    switch: s_left_shot_lane
    profile: lit_flash
    show_tokens:
      led: l_left_shot_lane
  select_quest_attack_right:
    switch: s_right_shot_lane
    profile: lit_flash
    show_tokens:
      led: l_right_shot_lane
  select_quest_scale_walls:
    switch: s_left_ramp
    profile: lit_flash
    show_tokens:
      led: l_left_ramp
  select_quest_mass_attack:
    switch: s_right_ramp
    profile: lit_flash
    show_tokens:
      led: l_right_ramp
  select_quest_drain_moat_left:
    switch: s_moat_left
    profile: lit_flash
    show_tokens:
      led: l_moat_left
  select_quest_drain_moat_right:
    switch: s_moat_right
    profile: lit_flash
    show_tokens:
      led: l_moat_right
  select_quest_quench_fire:
    switch: s_fire
    profile: lit_flash
    show_tokens:
      led: l_fire
