#config_version=6

shots:
  gather_mob_1:
    switch: s_mob_1
    profile: off_then_on_when_hit
    show_tokens:
      led: l_mob_1
  gather_mob_2:
    switch: s_mob_2
    profile: off_then_on_when_hit
    show_tokens:
      led: l_mob_2
  gather_mob_3:
    switch: s_mob_3
    profile: off_then_on_when_hit
    show_tokens:
      led: l_mob_3
